# Generated by Django 3.0.3 on 2020-02-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200227_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='movies.Movie'),
        ),
    ]
